### ISSUE TITLE
Figure out font licensing

### ISSUE THREAD

**Issue by cjneff** [staywoke/catalyst#29]
We're trying to license ProximaNova.

It's worth reaching out to the foundry, explaining what we're doing, and asking for a discount or free licensing.

**Comment by samswey** [comment]
How much is it to license Proxima Nova for this? Also, what's the contact info for the foundry?

**Comment by cjneff** [comment]
There’s a contact link at the bottom of this page: http://www.marksimonson.com/fonts/view/proxima-nova. I think it’s definitely worth reaching out.

From my brief research, it looks like it’s $29 per “weight” to license this for web use. My guess is that Jessica will end up choosing in the neighborhood of five weights.

**Comment by cjneff** [comment]
In the mean time: fontsquirrel.com

**Comment by samswey** [comment]
I just emailed Mark to ask if he'd be willing to give us Proxima Nova. Will get back to you when he responds.

-Sam

**Comment by samswey** [comment]
They are giving us five font weights of Proxima Nova for free. Which weights should we get?

-Sam
